### PR TITLE
Updated to 1.8

### PR DESCRIPTION
**Pull request by iLexiconn**

### CODE REVIEW

**Comment by SirTheori** [comment]
I see nothing wrong with this update, why is it not merged?

**Comment by shadowfacts** [comment]
Probably because the rest of the CoFH mods haven't update to 1.8. This will probably be merged once everything else is on 1.8.

**Comment by SirTheori** [comment]
OK, I was just wondering.

**Comment by KingLemming** [comment]
*If* we move to 1.8 at all. There's a good chance we'll port the RF API as a separate standalone for those who wish to partake in Mojang's mistake.

**Comment by Parker8283** [comment]
Formatting is what's wrong with this PR. Use the formatter in the Version repo.

I hope you at least don't hold back people who do want to update KL.

**Comment by KingLemming** [comment]
Can't merge this and your repo doesn't exist for me to look at it from that angle. I don't have a choice but to close this.

**Pull request closed without merging**
