### PR TITLE
Update to 1.8

### PR DESCRIPTION
**Pull request by laci200270**
Yes, I saw the another closed request, but now I think lot of mods waitning for this API

### CODE REVIEW

**Comment by shadowfacts** [comment]
@KingLemming has already stated that it is probable that CoFH won't be moving to 1.8. 
My suggestion is that you use @Vanhal's fork for additional inter mod compatibility.
https://github.com/Vanhal/RedstoneFlux-API-1.8

**Comment by laci200270** [comment]
So won't thermal expansion anytime for 1.8?And all CoFh mods will stay in 1.7.10?

**Comment by KingLemming** [comment]
Until Forge addresses the deficiencies in vanilla and lack of ForgeDirection, we really *cannot* go to 1.8, sorry.

There is no replacement for ForgeDirection.UNKNOWN, which is unacceptable.

**Comment by Parker8283** [comment]
null is the replacement, or it's at least what vanilla uses as it's UNKNOWN, which means you change your checks from unknown to null. What's the big deal here?

**Comment by laci200270** [comment]
This is a sounds good :+1:

**Comment by skyboy** [comment]
@Parker8283 Several places where there are no checks; ordinal is used as an index and UNKNOWN is a valid index for some purpose (possibly internal, possibly external); not to mention logic where the offsets are used raw without fear of null checks and writing the values to temporary variables to account for null. There are uses for null, this is *not* one of them.

**Comment by laci200270** [comment]
@skyboy why you not add to Cofh core your ForgeDirection replace?

**Comment by laci200270** [comment]
@skyboy LexManos said you don't need the unkown simply use null, and write null checks every place where you need it.

**Comment by skyboy** [comment]
That can be done, but I adamantly refuse being stupid with this logic. Directions enums should be strictly ***non*-null**.

**Comment by Parker8283** [comment]
In my mind, UNKNOWN and null are essentially the same. One just throws an NPE when someone fucks up.

**Comment by diesieben07** [comment]
I agree with Parker and the rest. `UNKNOWN` denotes an error condition and should not just silently be ignored with e.g. all-0-offsets, which can all cause all sorts of other crazy things to happen.

**Comment by laci200270** [comment]
:+1:

**Pull request closed without merging**
